//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Direct2Rep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_SaleRep
    {
        public int Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> SaleRepId { get; set; }
        public Nullable<System.DateTime> Creadted_At { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SaleRepresentative SaleRepresentative { get; set; }
    }
}
